; Auto-generated by breadbox. Do not edit.
; UART 6551: {{ component_id }} ({{ type }})
;
{% if type == "w65c51n" %}
{% if irq == "on" %}
; Driver: W65C51N, IRQ on (RX ring buffer, timed TX delay for TDRE bug workaround)
{% else %}
; Driver: W65C51N, polling (timed TX delay for TDRE bug workaround)
{% endif %}
{% else %}
{% if irq == "on" %}
; Driver: {{ type | upper }}, IRQ on (RX + TX ring buffers, hardware TDRE for TX flow)
{% else %}
; Driver: {{ type | upper }}, polling (TDRE poll for TX, RDRF poll for RX)
{% endif %}
{% endif %}
; Baud rate: {{ baudrate }}

{% set P = symbol_prefix %}

.include "hardware.inc"
.include "CORE/delay.inc"
.include "CORE/macros.inc"
.include "{{ component_path }}/macros.inc"
{% if pin_rts %}
.include "{{ pin_rts.component_path }}/macros.inc"
{% endif %}

.exportzp {{ symbol("byte") }}

.export {{ symbol("init") }}
.export {{ symbol("read") }}
.export {{ symbol("write") }}
.export {{ symbol("write_terminal") }}
.export {{ symbol("load_status") }}
.export {{ symbol("check_rx") }}
.export {{ symbol("check_tx") }}

.segment "KERNALZP" : zeropage

    {{ symbol("byte") }}: .res 1                ; Parameter byte for UART operations

.segment "KERNALROM"

    ; =====================================================================
    ; Soft reset the ACIA.
    ;
    ; Writing any value to the status register triggers a programmed reset.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("soft_reset") }}
        sta {{ P }}_STATUS
        DELAY_MS 100
        rts
    .endproc

; =========================================================================
; IC-specific driver code.
; =========================================================================

{% if type == "w65c51n" %}
.include "{{ component_path }}/_w65c51n.inc"
{% else %}
.include "{{ component_path }}/_generic.inc"
{% endif %}

    ; =====================================================================
    ; Write a byte to a terminal.
    ;
    ; Handles CR → CR+LF conversion for terminal-style output.
    ;
    ; In (zero page):
    ;   byte = data byte to transmit
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("write_terminal") }}
        lda {{ symbol("byte") }}
        cmp #$0d
        bne @raw

        ; Send CR first, then queue LF.
        jsr {{ symbol("write") }}
        lda #$0a
        sta {{ symbol("byte") }}
    @raw:
        jmp {{ symbol("write") }}
    .endproc
