; Auto-generated by breadbox. Do not edit.
; UART 6551: {{ device_id }} ({{ type }})
;
{% if irq == "on" %}
; Driver: W65C51N IRQ (RX ring buffer, timed TX delay for TDRE bug workaround)
{% else %}
; Driver: W65C51N polling (timed TX delay for TDRE bug workaround)
{% endif %}
; Baud rate: {{ baudrate }}
;
; All public procedures use {{ macro_prefix }}::byte (zero page) for parameter passing.
{% if irq == "on" %}
; Public API: init, read, write, write_terminal, load_status, check_rx, check_tx.
{% else %}
; Public API: init, read, write, write_terminal, load_status.
{% endif %}

{% set P = macro_prefix %}

.include "hardware.inc"
.include "core/delay.inc"
.include "core/macros.inc"
.include "{{ build_dir }}/macros.inc"
{% if pin_rts %}
.include "{{ pin_rts.build_dir }}/macros.inc"
{% endif %}

{% if irq == "on" %}
.segment "RAM"

    {{ P }}_rx_buffer: .res $100          ; 256-byte RX ring buffer

{% endif %}
.segment "ZEROPAGE"

    {{ P }}_byte: .res 1                ; Parameter byte for UART operations
{% if irq == "on" %}
    {{ P }}_rx_w_ptr:   .res 1          ; Ring buffer write pointer (IRQ side)
    {{ P }}_rx_r_ptr:   .res 1          ; Ring buffer read pointer (main side)
    {{ P }}_rx_pending: .res 1          ; Number of bytes waiting in buffer
    {{ P }}_rx_off:     .res 1          ; RTS deasserted flag (1 = flow stopped)
    {{ P }}_status:     .res 1          ; Cached status register from last IRQ
{% endif %}

.segment "KERNAL"

{% if type == "w65c51" %}
    ; =====================================================================
    ; TX character time (microseconds) for the W65C51N timed-TX workaround.
    ;
    ; The W65C51N has a hardware bug: the TDRE (Transmit Data Register Empty)
    ; status bit is never set. Polling it would spin forever. Instead, we
    ; delay for one full character time (10 bits at baud rate) after each
    ; write to allow the shift register to drain.

    _CHAR_TIME_US = 10000000 / {{ baudrate }}

    .proc _{{ P }}_tx_delay
        DELAY_US _CHAR_TIME_US
        rts
    .endproc

{% endif %}
    ; =====================================================================
    ; Soft reset the ACIA.
    ;
    ; Writing any value to the status register triggers a programmed reset.
    ;
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_soft_reset
        sta {{ P }}_STATUS
        DELAY_MS 100
        rts
    .endproc

{% if irq == "on" %}
    ; =====================================================================
    ; Initialize the UART (IRQ mode).
    ;
    ; Performs a soft reset, clears the ring buffer, configures baud rate
    ; and command register, asserts RTS, and enables CPU interrupts.
    ; The IRQ handler is registered via .interruptor (link-time CONDES table).
    ; Called automatically via .constructor.
    ;
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_init
        jsr _{{ P }}_soft_reset

        ; Clear ring buffer state.
        lda #0
        sta {{ P }}_rx_r_ptr
        sta {{ P }}_rx_w_ptr
        sta {{ P }}_rx_pending
        sta {{ P }}_rx_off
        lda {{ P }}_STATUS
        sta {{ P }}_status
{% if pin_rts %}

        ; Assert RTS: active low = ready to receive.
        {{ P }}_PIN_RTS_off
{% endif %}

        ; CTRL: 8N1, internal baud rate generator.
        lda #({{ P }}_CTRL_8BIT | {{ P }}_CTRL_1STOP | {{ P }}_CTRL_INTCLK | {{ P }}_CTRL_BAUD)
        sta {{ P }}_CTRL

        ; CMD: no parity, no echo, TX IRQ disabled (/RTS asserted), DTR on.
        ;      RX IRQ enabled.
        lda #({{ P }}_CMD_TIC2 | {{ P }}_CMD_DTR)
        sta {{ P }}_CMD

        ; Enable CPU interrupts. The IRQ handler is registered at link time
        ; via .interruptor and dispatched by the core interruptor table.
        cli

        rts
    .endproc
    .constructor _{{ P }}_init

    ; =====================================================================
    ; IRQ handler.
    ;
    ; Called by the core IRQ dispatcher when an interrupt occurs. Reads the
    ; ACIA status register (acknowledges the IRQ), caches it, and dispatches
    ; to the RX handler if this ACIA caused the interrupt.
    ;
    ; Register saving and RTI are handled by the core dispatcher.

    .proc _{{ P }}_irq_handler
        lda {{ P }}_STATUS
        sta {{ P }}_status
        and #{{ P }}_SR_IRQ
        beq @done
        lda {{ P }}_status
        jsr _{{ P }}_irq_handler_rx
    @done:
        rts
    .endproc
    .interruptor _{{ P }}_irq_handler

    ; =====================================================================
    ; IRQ RX handler.
    ;
    ; If the receive data register is full, reads the byte and stores it
    ; in the ring buffer. Then checks whether to deassert RTS (stop flow)
    ; if the buffer is getting full.
    ;
    ; In:
    ;   A = status register value (from irq_handler)

    .proc _{{ P }}_irq_handler_rx
        and #{{ P }}_SR_RDRF
        beq @done

        lda {{ P }}_DATA
        ldx {{ P }}_rx_w_ptr
        sta {{ P }}_rx_buffer,X
        inc {{ P }}_rx_w_ptr
        inc {{ P }}_rx_pending

        jsr _{{ P }}_turn_rx_off_if_buffer_almost_full

    @done:
        rts
    .endproc
{% if pin_rts %}

    ; =====================================================================
    ; Deassert RTS if the receive buffer is almost full (~80%).
    ;
    ; Called from the IRQ handler. When rx_pending reaches $D0 (208 of 256),
    ; sets the RTS pin high (deasserted = stop sending) to prevent overflow.

    .proc _{{ P }}_turn_rx_off_if_buffer_almost_full
        lda {{ P }}_rx_off
        bne @done

        lda {{ P }}_rx_pending
        cmp #$d0
        bcc @done

        lda #1
        sta {{ P }}_rx_off
        {{ P }}_PIN_RTS_on

    @done:
        rts
    .endproc

    ; =====================================================================
    ; Reassert RTS if the receive buffer is draining (~30%).
    ;
    ; Called from the read proc (main context). When rx_pending drops below
    ; $50 (80 of 256) and RTS was deasserted, reasserts RTS (pin low = ready)
    ; under sei/cli to avoid races with the IRQ handler.

    .proc _{{ P }}_turn_rx_on_if_buffer_emptying
        lda {{ P }}_rx_off
        beq @done

        lda {{ P }}_rx_pending
        cmp #$50
        bcs @done

        sei
        lda #0
        sta {{ P }}_rx_off
        {{ P }}_PIN_RTS_off
        cli

    @done:
        rts
    .endproc
{% endif %}

    ; =====================================================================
    ; Read a byte from the receive ring buffer (non-blocking).
    ;
    ; If the buffer contains data, reads the next byte, advances the read
    ; pointer, decrements the pending count, and checks whether to reassert
    ; RTS flow control.
    ;
    ; Out:
    ;   C = 1 if byte received, 0 if buffer empty
    ;   byte = received data (valid only when C=1)
    ;   A, X = clobbered

    .proc _{{ P }}_read
        clc
        lda {{ P }}_rx_pending
        beq @done

        ldx {{ P }}_rx_r_ptr
        lda {{ P }}_rx_buffer,X
        sta {{ P }}_byte

        inc {{ P }}_rx_r_ptr
        dec {{ P }}_rx_pending
{% if pin_rts %}

        jsr _{{ P }}_turn_rx_on_if_buffer_emptying
{% endif %}
        sec

    @done:
        rts
    .endproc

    ; =====================================================================
    ; Check how many bytes are pending in the receive buffer.
    ;
    ; Out:
    ;   byte = number of bytes waiting
    ;   A = clobbered

    .proc _{{ P }}_check_rx
        lda {{ P }}_rx_pending
        sta {{ P }}_byte
        rts
    .endproc

    ; =====================================================================
    ; Check whether the transmitter is ready.
    ;
    ; For the W65C51N IRQ driver, TX is always timed (no hardware TDRE),
    ; so we always report ready.
    ;
    ; Out:
    ;   byte = 1 (always ready)
    ;   A = clobbered

    .proc _{{ P }}_check_tx
        lda #1
        sta {{ P }}_byte
        rts
    .endproc

    ; =====================================================================
    ; Load the cached ACIA status register into the byte variable.
    ;
    ; In IRQ mode the status register is read by the IRQ handler and
    ; cached in a ZP variable to avoid side effects from re-reading.
    ;
    ; Out:
    ;   byte = cached status register contents
    ;   A = clobbered

    .proc _{{ P }}_load_status
        lda {{ P }}_status
        sta {{ P }}_byte
        rts
    .endproc

{% else %}
    ; =====================================================================
    ; Initialize the UART (polling mode).
    ;
    ; Performs a soft reset, configures baud rate and command register,
    ; and asserts the RTS flow control pin (if present).
    ; Called automatically via .constructor.
    ;
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_init
        jsr _{{ P }}_soft_reset
{% if pin_rts %}

        ; Assert RTS: active low = ready to receive.
        {{ P }}_PIN_RTS_off
{% endif %}

        ; CTRL: 8N1, internal baud rate generator.
        lda #({{ P }}_CTRL_8BIT | {{ P }}_CTRL_1STOP | {{ P }}_CTRL_INTCLK | {{ P }}_CTRL_BAUD)
        sta {{ P }}_CTRL

        ; CMD: no parity, no echo, TX IRQ disabled (/RTS asserted), DTR on.
        ;      RX IRQ disabled for polling mode.
        lda #({{ P }}_CMD_TIC2 | {{ P }}_CMD_DTR | {{ P }}_CMD_IRQOFF)
        sta {{ P }}_CMD

        rts
    .endproc
    .constructor _{{ P }}_init

    ; =====================================================================
    ; Read a byte from the receiver (non-blocking).
    ;
    ; Checks the RDRF status bit. If a byte is waiting, reads it into
    ; the byte variable and returns with carry set. Otherwise returns
    ; with carry clear.
    ;
    ; Out:
    ;   C = 1 if byte received, 0 if buffer empty
    ;   byte = received data (valid only when C=1)
    ;   A = clobbered

    .proc _{{ P }}_read
        clc
        lda {{ P }}_STATUS
        and #{{ P }}_SR_RDRF
        beq @done

        lda {{ P }}_DATA
        sta {{ P }}_byte
        sec
    @done:
        rts
    .endproc

    ; =====================================================================
    ; Load the ACIA status register into the byte variable.
    ;
    ; Out:
    ;   byte = status register contents
    ;   A = clobbered

    .proc _{{ P }}_load_status
        lda {{ P }}_STATUS
        sta {{ P }}_byte
        rts
    .endproc

{% endif %}
    ; =====================================================================
    ; Write a byte to the transmitter.
    ;
{% if type == "w65c51" %}
    ; After writing, delays for one character time to work around the
    ; W65C51N TDRE bug (the shift register must drain before the next write).
    ;
{% endif %}
    ; In (zero page):
    ;   byte = data byte to transmit
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_write
        lda {{ P }}_byte
        sta {{ P }}_DATA
{% if type == "w65c51" %}
        jsr _{{ P }}_tx_delay
{% endif %}
        rts
    .endproc

    ; =====================================================================
    ; Write a byte to a terminal.
    ;
    ; Handles CR → CR+LF conversion for terminal-style output.
    ;
    ; In (zero page):
    ;   byte = data byte to transmit
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_write_terminal
        lda {{ P }}_byte
        cmp #$0d
        bne @raw

        ; Send CR first, then queue LF.
        jsr _{{ P }}_write
        lda #$0a
        sta {{ P }}_byte
    @raw:
        jmp _{{ P }}_write
    .endproc

; =========================================================================
; Exports
; =========================================================================

{{ exportzp("_byte") }}

{{ export("_init") }}
{{ export("_read") }}
{{ export("_write") }}
{{ export("_write_terminal") }}
{{ export("_load_status") }}
{% if irq == "on" %}
{{ export("_check_rx") }}
{{ export("_check_tx") }}
{% endif %}
