; Auto-generated by breadbox. Do not edit.
; UART 6551: {{ device_id }} ({{ type }})
;
{% if type == "w65c51" %}
{% if irq == "on" %}
; Driver: W65C51N IRQ (RX ring buffer, timed TX delay for TDRE bug workaround)
{% else %}
; Driver: W65C51N polling (timed TX delay for TDRE bug workaround)
{% endif %}
{% elif type in ("um6551", "m6551") %}
{% if irq == "on" %}
; Driver: UM6551 IRQ (RX + TX ring buffers, hardware TDRE for TX flow)
{% else %}
; Driver: UM6551 polling (TDRE poll for TX, RDRF poll for RX)
{% endif %}
{% endif %}
; Baud rate: {{ baudrate }}
;
; All public procedures use {{ macro_prefix }}::byte (zero page) for parameter passing.
; Public API: init, read, write, write_terminal, load_status, check_rx, check_tx.

{% set P = macro_prefix %}

.include "hardware.inc"
.include "CORE/delay.inc"
.include "CORE/macros.inc"
.include "{{ device_path }}/macros.inc"
{% if pin_rts %}
.include "{{ pin_rts.device_path }}/macros.inc"
{% endif %}

.segment "ZEROPAGE"

    {{ P }}_byte: .res 1                ; Parameter byte for UART operations

.segment "KERNAL"

    ; =====================================================================
    ; Soft reset the ACIA.
    ;
    ; Writing any value to the status register triggers a programmed reset.
    ;
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_soft_reset
        sta {{ P }}_STATUS
        DELAY_MS 100
        rts
    .endproc

; =========================================================================
; IC-specific driver code.
; =========================================================================

{% if type == "w65c51" %}
.include "{{ device_path }}/_w65c51n.inc"
{% elif type in ("um6551", "m6551") %}
.include "{{ device_path }}/_um6551.inc"
{% endif %}

    ; =====================================================================
    ; Write a byte to a terminal.
    ;
    ; Handles CR → CR+LF conversion for terminal-style output.
    ;
    ; In (zero page):
    ;   byte = data byte to transmit
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_write_terminal
        lda {{ P }}_byte
        cmp #$0d
        bne @raw

        ; Send CR first, then queue LF.
        jsr _{{ P }}_write
        lda #$0a
        sta {{ P }}_byte
    @raw:
        jmp _{{ P }}_write
    .endproc

; =========================================================================
; Exports
; =========================================================================

{{ exportzp("_byte") }}

{{ export("_init") }}
{{ export("_read") }}
{{ export("_write") }}
{{ export("_write_terminal") }}
{{ export("_load_status") }}
{{ export("_check_rx") }}
{{ export("_check_tx") }}
