; Auto-generated by breadbox. Do not edit.
; HD44780 LCD: {{ component_id }} ({{ mode }} mode)
;
; Control: {{ ctrl.component_path }} (RS+RWB), {{ pin_en.component_path }} (EN)
; Data bus: {{ data.component_path }}
;
; Public write/write_cmnd take the data byte in A.
; Public API: init, write_cmnd, write, clr, home, print.
; Call via JSR, e.g. `jsr {{ symbol_prefix }}::write`.

{% set P = symbol_prefix %}
{% set CTRL_P = ctrl.symbol_prefix %}
{% set DATA_P = data.symbol_prefix %}
{% set IS_4BIT = (mode == "4bit") %}

.include "hardware.inc"
.include "CORE/delay.inc"
.include "{{ component_path }}/macros.inc"
.include "{{ data.component_path }}/macros.inc"
.include "{{ ctrl.component_path }}/macros.inc"
.include "{{ pin_en.component_path }}/macros.inc"

; CTRL pin ordering: pins[0]=RS, pins[1]=RWB (set by LCD resolver).
{% set RS_PIN = ctrl.pins[0] %}
{% set RWB_PIN = ctrl.pins[1] %}

;                                                      RS RWB
{{ P }}_CTRL_CMD_WR  = $00                            ; 0  0  write command
{{ P }}_CTRL_CMD_RD  = {{ CTRL_P }}_BIT_{{ RWB_PIN }}           ; 0  1  read status
{{ P }}_CTRL_DATA_WR = {{ CTRL_P }}_BIT_{{ RS_PIN }}            ; 1  0  write data
{{ P }}_CTRL_DATA_RD = {{ CTRL_P }}_BIT_{{ RS_PIN }} | {{ CTRL_P }}_BIT_{{ RWB_PIN }}  ; 1  1  read data

.exportzp {{ symbol("ptr") }}

.export {{ symbol("init") }}
.export {{ symbol("write_cmnd") }}
.export {{ symbol("write") }}
.export {{ symbol("clr") }}
.export {{ symbol("home") }}
.export {{ symbol("print") }}

.segment "ZEROPAGE" : zeropage

    {{ symbol("ptr") }}:  .res 2            ; Pointer for string printing
    {{ symbol("tmp") }}:  .res 1            ; Internal temporary

.segment "KERNALROM"

    ; =========================================================================
    ; Private: pulse EN high then low.
    ;
    ; The GPIO pin macros include sufficient instruction cycles for the
    ; HD44780's minimum EN pulse width (450ns). At 1 MHz each instruction
    ; takes 2-6 µs, so no extra delays are needed.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("pulse_en") }}
        {{ P }}_PIN_EN_on
        {{ P }}_PIN_EN_off
        rts
    .endproc

{% if IS_4BIT %}
    ; =========================================================================
    ; Private: write a byte as two nibbles to the 4-bit data bus.
    ;
    ; The register select (RS) must already be configured by the caller.
    ; Sends the high nibble first, then the low nibble, with EN pulses.
    ;
    ; In (zero page):
    ;   {{ symbol("tmp") }} = byte to send
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("write_nibbles") }}
        ; High nibble: upper 4 bits are already in position.
        lda {{ symbol("tmp") }}
        and #$F0
        {{ DATA_P }}_write_a
        jsr {{ symbol("pulse_en") }}

        ; Low nibble: shift lower 4 bits into upper position.
        lda {{ symbol("tmp") }}
        asl
        asl
        asl
        asl
        {{ DATA_P }}_write_a
        jsr {{ symbol("pulse_en") }}

        rts
    .endproc

{% endif %}
    ; =========================================================================
    ; Private: write a raw byte to the data bus (used during init only).
    ;
    ; During the power-up sequence the LCD is in 8-bit mode regardless of the
    ; target configuration. This writes data and pulses EN, without checking
    ; the busy flag.
    ;
    ; In (zero page):
    ;   {{ symbol("tmp") }} = byte to write
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("write_init") }}
        lda {{ symbol("tmp") }}
        {{ DATA_P }}_write_a
        jsr {{ symbol("pulse_en") }}
        rts
    .endproc

    ; =========================================================================
    ; Private: power up sequence — force LCD into 8-bit mode.
    ;
    ; Sends Function Set (DL=1) three times with required delays.
    ; This guarantees a known state regardless of the LCD's power-on condition.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("power_up") }}
        ; Wait >15 ms after Vcc rises before sending any commands.
        DELAY_MS 20

        ; Function Set for turning on 8-bit mode.
        lda #$30
        sta {{ symbol("tmp") }}

        ; 1st Function Set — wait >4.1 ms afterward.
        jsr {{ symbol("write_init") }}
        DELAY_MS 5

        ; 2nd Function Set — wait >100 µs afterward.
        jsr {{ symbol("write_init") }}
        DELAY_US 200

        ; 3rd Function Set — LCD is now reliably in 8-bit mode.
        jsr {{ symbol("write_init") }}
        DELAY_US 200

        rts
    .endproc

{% if IS_4BIT %}
    ; =========================================================================
    ; Private: switch LCD from 8-bit to 4-bit mode.
    ;
    ; Sends a single nibble ($20 = Function Set with DL=0) while the LCD is
    ; still in 8-bit mode. After this, all commands use two-nibble transfers.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("enable_4bit") }}
        lda #$20
        sta {{ symbol("tmp") }}
        jsr {{ symbol("write_init") }}
        DELAY_US 200
        rts
    .endproc

{% endif %}
    ; =========================================================================
    ; Private: configure display parameters.
    ;
    ; Sends Function Set, Display On, and Entry Mode Set commands.
    ; Must be called after the LCD is in the correct bus mode.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("configure") }}
        lda #{{ P }}_CMD_FUNCSET
        sta {{ symbol("tmp") }}
        jsr {{ symbol("wait_ready") }}
        jsr {{ symbol("write_cmnd_raw") }}

        lda #{{ P }}_CMD_DISPLAY_ON
        sta {{ symbol("tmp") }}
        jsr {{ symbol("wait_ready") }}
        jsr {{ symbol("write_cmnd_raw") }}

        lda #{{ P }}_CMD_ENTRYMODE
        sta {{ symbol("tmp") }}
        jsr {{ symbol("wait_ready") }}
        jsr {{ symbol("write_cmnd_raw")}}

        rts
    .endproc

    ; =========================================================================
    ; Private: write command byte without busy-flag check.
    ;
    ; Sets RS=0 (command), RWB=0 (write), writes data, pulses EN.
    ; Used internally — public API should use write_cmnd which polls BF.
    ;
    ; In (zero page):
    ;   {{ symbol("tmp") }} = command byte to write
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("write_cmnd_raw") }}
        {{ CTRL_P }}_write {{ P }}_CTRL_CMD_WR
{% if IS_4BIT %}
        jsr {{ symbol("write_nibbles") }}
{% else %}
        lda {{ symbol("tmp") }}
        {{ DATA_P }}_write_a
        jsr {{ symbol("pulse_en") }}
{% endif %}
        rts
    .endproc

    ; =========================================================================
    ; Private: poll busy flag until the LCD is ready.
    ;
    ; Reads the busy flag (D7) by switching the data bus to input,
    ; setting RWB=1 (read mode), and pulsing EN. Loops until BF=0.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("wait_ready") }}
    @loop:
        ; Switch data pins to input.
        {{ DATA_P }}_set_input

        ; Set control: RS=0 (status), RWB=1 (read).
        {{ CTRL_P }}_write {{ P }}_CTRL_CMD_RD

        ; Pulse EN high and read the data port.
        {{ P }}_PIN_EN_on
        {{ DATA_P }}_read_port
        pha                          ; save status byte
        {{ P }}_PIN_EN_off

{% if IS_4BIT %}
        ; Clock out the low nibble (ignored).
        jsr {{ symbol("pulse_en") }}
{% endif %}

        ; Restore data pins to output.
        {{ DATA_P }}_set_output

        ; Restore control to write mode.
        {{ CTRL_P }}_write {{ P }}_CTRL_CMD_WR

        ; Check busy flag.
        pla
        and #{{ P }}_BUSY_FLAG
        bne @loop

        rts
    .endproc

; =========================================================================
; Public API
; =========================================================================

    ; =====================================================================
    ; Initialize the LCD display.
    ;
    ; Performs the full power-up sequence, configures the display mode,
    ; and clears the screen. Called automatically via .constructor.
    ;
    ; Out:
    ;   A, X, Y = clobbered

    .proc {{ symbol("init") }}
        ; Set data pins to output.
        {{ DATA_P }}_set_output

        ; Set control pins low (EN=0, CTRL=CMD_WR).
        {{ P }}_PIN_EN_off
        {{ CTRL_P }}_write {{ P }}_CTRL_CMD_WR

        ; Power-up: force LCD into known 8-bit state.
        jsr {{ symbol("power_up") }}

{% if IS_4BIT %}
        ; Switch to 4-bit mode.
        jsr {{ symbol("enable_4bit") }}
{% endif %}

        ; Configure display parameters.
        jsr {{ symbol("configure") }}

        ; Clear screen.
        lda #{{ P }}_CMD_CLEAR
        sta {{ symbol("tmp") }}
        jsr {{ symbol("wait_ready") }}
        jsr {{ symbol("write_cmnd_raw") }}

        rts
    .endproc
    .constructor {{ symbol("init") }}

    ; =====================================================================
    ; Write a command byte to the LCD.
    ;
    ; Waits for the LCD to be ready, then sends the command.
    ;
    ; In:
    ;   A = command byte
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("write_cmnd") }}
        sta {{ symbol("tmp") }}
        jsr {{ symbol("wait_ready") }}
        jsr {{ symbol("write_cmnd_raw") }}
        rts
    .endproc

    ; =====================================================================
    ; Write a data byte to the LCD (character output).
    ;
    ; Waits for the LCD to be ready, sets RS=1 (data), then sends the byte.
    ;
    ; In:
    ;   A = data byte
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("write") }}
        sta {{ symbol("tmp") }}
        jsr {{ symbol("wait_ready") }}
        ; RS=1 (data register), RWB=0 (write).
        {{ CTRL_P }}_write {{ P }}_CTRL_DATA_WR

{% if IS_4BIT %}
        jsr {{ symbol("write_nibbles") }}
{% else %}
        lda {{ symbol("tmp") }}
        {{ DATA_P }}_write_a
        jsr {{ symbol("pulse_en") }}
{% endif %}
        rts
    .endproc

    ; =====================================================================
    ; Clear the display and return cursor to home.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("clr") }}
        lda #{{ P }}_CMD_CLEAR
        jsr {{ symbol("write_cmnd") }}
        rts
    .endproc

    ; =====================================================================
    ; Return cursor to home position.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("home") }}
        lda #{{ P }}_CMD_HOME
        jsr {{ symbol("write_cmnd") }}
        rts
    .endproc

    ; =====================================================================
    ; Print a null-terminated string.
    ;
    ; In (zero page):
    ;   {{ symbol("ptr") }} = pointer to null-terminated string
    ; Out:
    ;   A, Y = clobbered

    .proc {{ symbol("print") }}
        ldy #0
@loop:  lda ({{ symbol("ptr") }}),y
        beq @done
        phy
        jsr {{ symbol("write") }}
        ply
        iny
        bne @loop
@done:  rts
    .endproc
