; Auto-generated by breadbox. Do not edit.
; HD44780 LCD: {{ device_id }} ({{ mode }} mode)
;
; Control: CTRL group (RS+RWB) on {{ ctrl.port }}, EN={{ pin_en.pin }}
; Data bus: {{ data.device_path }} (port {{ data.port }} on {{ data.bus_device.id }}, mask {{ data.bits | hex }})
;
; All public procedures use {{ macro_prefix }}::byte (zero page) for parameter passing.
; Public API: init, write_cmnd, write, clr, home, print.
; Call via JSR, e.g. `jsr {{ macro_prefix }}::write`.

{% set P = macro_prefix %}
{% set CTRL_P = ctrl.device_path | replace("::", "_") %}
{% set DATA_P = data.device_path | replace("::", "_") %}
{% set IS_4BIT = (mode == "4bit") %}

.include "hardware.inc"
.include "core/delay.inc"
.include "{{ build_dir }}/macros.inc"
.include "{{ data.build_dir }}/macros.inc"
.include "{{ ctrl.build_dir }}/macros.inc"
.include "{{ pin_en.build_dir }}/macros.inc"

.segment "ZEROPAGE"

    {{ P }}_byte: .res 1                ; Parameter byte for LCD operations
    {{ P }}_ptr:  .res 2                ; Pointer for string printing
    {{ P }}_tmp:  .res 1                ; Internal temporary

.segment "KERNAL"

    ; =========================================================================
    ; Private: pulse EN high then low.
    ;
    ; The GPIO pin macros include sufficient instruction cycles for the
    ; HD44780's minimum EN pulse width (450ns). At 1 MHz each instruction
    ; takes 2-6 µs, so no extra delays are needed.
    ;
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_pulse_en
        {{ P }}_PIN_EN_on
        {{ P }}_PIN_EN_off
        rts
    .endproc

{% if IS_4BIT %}
    ; =========================================================================
    ; Private: write a byte as two nibbles to the 4-bit data bus.
    ;
    ; The register select (RS) must already be configured by the caller.
    ; Sends the high nibble first, then the low nibble, with EN pulses.
    ;
    ; In (zero page):
    ;   {{ P }}_byte = byte to send
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_write_nibbles
        ; High nibble: upper 4 bits are already in position.
        lda {{ P }}_byte
        and #$F0
        {{ DATA_P }}_write_a
        jsr _{{ P }}_pulse_en

        ; Low nibble: shift lower 4 bits into upper position.
        lda {{ P }}_byte
        asl
        asl
        asl
        asl
        {{ DATA_P }}_write_a
        jsr _{{ P }}_pulse_en

        rts
    .endproc

{% endif %}
    ; =========================================================================
    ; Private: write a raw byte to the data bus (used during init only).
    ;
    ; During the power-up sequence the LCD is in 8-bit mode regardless of the
    ; target configuration. This writes data and pulses EN, without checking
    ; the busy flag.
    ;
    ; In (zero page):
    ;   {{ P }}_byte = byte to write
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_write_init
        lda {{ P }}_byte
        {{ DATA_P }}_write_a
        jsr _{{ P }}_pulse_en
        rts
    .endproc

    ; =========================================================================
    ; Private: power up sequence — force LCD into 8-bit mode.
    ;
    ; Sends Function Set (DL=1) three times with required delays.
    ; This guarantees a known state regardless of the LCD's power-on condition.
    ;
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_power_up
        ; Wait >15 ms after Vcc rises before sending any commands.
        DELAY_MS 20

        ; Function Set for turning on 8-bit mode.
        lda #$30
        sta {{ P }}_byte

        ; 1st Function Set — wait >4.1 ms afterward.
        jsr _{{ P }}_write_init
        DELAY_MS 5

        ; 2nd Function Set — wait >100 µs afterward.
        jsr _{{ P }}_write_init
        DELAY_US 200

        ; 3rd Function Set — LCD is now reliably in 8-bit mode.
        jsr _{{ P }}_write_init
        DELAY_US 200

        rts
    .endproc

{% if IS_4BIT %}
    ; =========================================================================
    ; Private: switch LCD from 8-bit to 4-bit mode.
    ;
    ; Sends a single nibble ($20 = Function Set with DL=0) while the LCD is
    ; still in 8-bit mode. After this, all commands use two-nibble transfers.
    ;
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_enable_4bit
        lda #$20
        sta {{ P }}_byte
        jsr _{{ P }}_write_init
        DELAY_US 200
        rts
    .endproc

{% endif %}
    ; =========================================================================
    ; Private: configure display parameters.
    ;
    ; Sends Function Set, Display On, and Entry Mode Set commands.
    ; Must be called after the LCD is in the correct bus mode.
    ;
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_configure
        lda #{{ P }}_CMD_FUNCSET
        sta {{ P }}_byte
        jsr _{{ P }}_wait_ready
        jsr _{{ P }}_write_cmnd_raw

        lda #{{ P }}_CMD_DISPLAY_ON
        sta {{ P }}_byte
        jsr _{{ P }}_wait_ready
        jsr _{{ P }}_write_cmnd_raw

        lda #{{ P }}_CMD_ENTRYMODE
        sta {{ P }}_byte
        jsr _{{ P }}_wait_ready
        jsr _{{ P }}_write_cmnd_raw

        rts
    .endproc

    ; =========================================================================
    ; Private: write command byte without busy-flag check.
    ;
    ; Sets RS=0 (command), RWB=0 (write), writes data, pulses EN.
    ; Used internally — public API should use write_cmnd which polls BF.
    ;
    ; In (zero page):
    ;   {{ P }}_byte = command byte to write
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_write_cmnd_raw
        {{ CTRL_P }}_write {{ P }}_CTRL_CMD_WR
{% if IS_4BIT %}
        jsr _{{ P }}_write_nibbles
{% else %}
        lda {{ P }}_byte
        {{ DATA_P }}_write_a
        jsr _{{ P }}_pulse_en
{% endif %}
        rts
    .endproc

    ; =========================================================================
    ; Private: poll busy flag until the LCD is ready.
    ;
    ; Reads the busy flag (D7) by switching the data bus to input,
    ; setting RWB=1 (read mode), and pulsing EN. Loops until BF=0.
    ;
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_wait_ready
    @loop:
        ; Switch data pins to input.
        {{ DATA_P }}_set_input

        ; Set control: RS=0 (status), RWB=1 (read).
        {{ CTRL_P }}_write {{ P }}_CTRL_CMD_RD

        ; Pulse EN high and read the data port.
        {{ P }}_PIN_EN_on
        {{ DATA_P }}_read_port
        pha                          ; save status byte
        {{ P }}_PIN_EN_off

{% if IS_4BIT %}
        ; Clock out the low nibble (ignored).
        jsr _{{ P }}_pulse_en
{% endif %}

        ; Restore data pins to output.
        {{ DATA_P }}_set_output

        ; Restore control to write mode.
        {{ CTRL_P }}_write {{ P }}_CTRL_CMD_WR

        ; Check busy flag.
        pla
        and #{{ P }}_BUSY_FLAG
        bne @loop

        rts
    .endproc

; =========================================================================
; Public API
; =========================================================================

    ; =====================================================================
    ; Initialize the LCD display.
    ;
    ; Performs the full power-up sequence, configures the display mode,
    ; and clears the screen. Called automatically via .constructor.
    ;
    ; Out:
    ;   A, X, Y = clobbered

    .proc _{{ P }}_init
        ; Set data pins to output.
        {{ DATA_P }}_set_output

        ; Set control pins low (EN=0, CTRL=CMD_WR).
        {{ P }}_PIN_EN_off
        {{ CTRL_P }}_write {{ P }}_CTRL_CMD_WR

        ; Power-up: force LCD into known 8-bit state.
        jsr _{{ P }}_power_up

{% if IS_4BIT %}
        ; Switch to 4-bit mode.
        jsr _{{ P }}_enable_4bit
{% endif %}

        ; Configure display parameters.
        jsr _{{ P }}_configure

        ; Clear screen.
        lda #{{ P }}_CMD_CLEAR
        sta {{ P }}_byte
        jsr _{{ P }}_wait_ready
        jsr _{{ P }}_write_cmnd_raw

        rts
    .endproc
    .constructor _{{ P }}_init

    ; =====================================================================
    ; Write a command byte to the LCD.
    ;
    ; Waits for the LCD to be ready, then sends the command.
    ;
    ; In (zero page):
    ;   {{ P }}_byte = command byte
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_write_cmnd
        jsr _{{ P }}_wait_ready
        jsr _{{ P }}_write_cmnd_raw
        rts
    .endproc

    ; =====================================================================
    ; Write a data byte to the LCD (character output).
    ;
    ; Waits for the LCD to be ready, sets RS=1 (data), then sends the byte.
    ;
    ; In (zero page):
    ;   {{ P }}_byte = data byte
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_write
        jsr _{{ P }}_wait_ready

        ; RS=1 (data register), RWB=0 (write).
        {{ CTRL_P }}_write {{ P }}_CTRL_DATA_WR

{% if IS_4BIT %}
        jsr _{{ P }}_write_nibbles
{% else %}
        lda {{ P }}_byte
        {{ DATA_P }}_write_a
        jsr _{{ P }}_pulse_en
{% endif %}
        rts
    .endproc

    ; =====================================================================
    ; Clear the display and return cursor to home.
    ;
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_clr
        lda #{{ P }}_CMD_CLEAR
        sta {{ P }}_byte
        jsr _{{ P }}_write_cmnd
        rts
    .endproc

    ; =====================================================================
    ; Return cursor to home position.
    ;
    ; Out:
    ;   A = clobbered

    .proc _{{ P }}_home
        lda #{{ P }}_CMD_HOME
        sta {{ P }}_byte
        jsr _{{ P }}_write_cmnd
        rts
    .endproc

    ; =====================================================================
    ; Print a null-terminated string.
    ;
    ; In (zero page):
    ;   {{ P }}_ptr = pointer to null-terminated string
    ; Out:
    ;   A, Y = clobbered

    .proc _{{ P }}_print
        ldy #0
@loop:  lda ({{ P }}_ptr),y
        beq @done
        sta {{ P }}_byte
        phy
        jsr _{{ P }}_write
        ply
        iny
        bne @loop
@done:  rts
    .endproc

; =========================================================================
; Exports
; =========================================================================

{{ exportzp("_byte") }}
{{ exportzp("_ptr") }}

{{ export("_init") }}
{{ export("_write_cmnd") }}
{{ export("_write") }}
{{ export("_clr") }}
{{ export("_home") }}
{{ export("_print") }}
