{{ symbol("API_S") }} = 1
.include "{{ component_path }}/api.inc"

.import   main                       ; The subroutine to start after initialization
.import   __CONSTRUCTOR_TABLE__      ; Constructor table (generated by ld65 CONDES)
.import   __CONSTRUCTOR_COUNT__      ; Number of constructor entries

.export {{ symbol("boot") }}
.export {{ symbol("halt") }}

.segment "ZEROPAGE"

    {{ symbol("constructor_ptr") }}:.res 2          ; Target address for trampoline construction
    {{ symbol("condes_ptr") }}:     .res 2          ; Pointer into constructor table (boot only)

.segment "KERNALROM"

    ; =========================================================================
    ; KERNAL Boot sequence
    ;
    ; Provides the boot subroutine (jumped to by reset vector) and the
    ; halt loop. The boot sequence calls all registered constructors
    ; (sorted by descending priority) and then jumps to `main`, which
    ; must be implemented by the project that is built on top of BREADBOX.

    .proc {{ symbol("boot") }}
        ldx #$ff                               ; Initialize stack pointer.
        txs
        cld                                    ; Disable decimal mode.
        jsr {{ symbol("call_constructors") }}  ; Call registered constructors.
        jmp main                               ; Call main (exported by project).
    .endproc

    ; =========================================================================
    ; Halt program execution.
    ;
    ; Use the `HALT` macro to jump to this function.

    .proc {{ symbol("halt") }}
        sei                          ; Interrupts handling must not break loop.
    @loop:                           ; Loop indefinitely.
        jmp @loop
    .endproc

    ; =========================================================================
    ; Call all registered constructors.
    ;
    ; The CONDES table is generated by ld65, sorted by descending priority.
    ; Each entry is 2 bytes: address low + address high.
    ; Uses the trampoline for indirect JSR calls.

    .proc {{ symbol("call_constructors") }}
        lda #<__CONSTRUCTOR_COUNT__
        beq @done

        ; Initialize pointer to constructor table.
        CP_ADDRESS {{ symbol("condes_ptr") }}, __CONSTRUCTOR_TABLE__

        ldx #<__CONSTRUCTOR_COUNT__
    @loop:
        ; Read address from table entry (2 bytes: lo, hi).
        ldy #0
        lda ({{ symbol("condes_ptr") }}),y          ; Address low byte.
        sta {{ symbol("constructor_ptr") }}
        iny
        lda ({{ symbol("condes_ptr") }}),y          ; Address high byte.
        sta {{ symbol("constructor_ptr") }} + 1

        ; Save counter, call constructor, restore counter.
        txa
        pha
        jsr {{ symbol("constructor_trampoline") }}
        pla
        tax

        ; Advance pointer by 2 bytes (next entry).
        clc
        lda {{ symbol("condes_ptr") }}
        adc #2
        sta {{ symbol("condes_ptr") }}
        bcc @no_carry
        inc {{ symbol("condes_ptr") }}+1
    @no_carry:

        dex
        bne @loop

    @done:
        rts
    .endproc

    ; =========================================================================
    ; Classic 6502 JSR trampoline.
    ;
    ; The 6502 has no `JSR (indirect)` instruction. Work around this by
    ; doing a `jsr` into a subroutine (the trampoline) that then does a `jmp`
    ; to the target subroutine address. When that subroutine does its `rts`,
    ; the program pointer returns to the point from where the `jsr` was done.

    .proc {{ symbol("constructor_trampoline") }}
        jmp ({{ symbol("constructor_ptr") }})
    .endproc
