.include "{{ component_path }}/coding_macros.inc"
.include "{{ component_path }}/delay_macros.inc"

.import   main                       ; The subroutine to start after initialization
.import   __CONSTRUCTOR_TABLE__      ; Constructor table (generated by ld65 CONDES)
.import   __CONSTRUCTOR_COUNT__      ; Number of constructor entries

.segment "ZEROPAGE"

    {{ my("constructor_ptr") }}:.res 2          ; Target address for trampoline construction
    {{ my("condes_ptr") }}:     .res 2          ; Pointer into constructor table (boot only)

.segment "KERNALROM"

    ; =========================================================================
    ; KERNAL Boot sequence
    ;
    ; Provides the boot subroutine (jumped to by reset vector). The boot
    ; sequence calls all registered constructors (sorted by descending priority)
    ; and then jumps to `main`, which must be implemented by the project that
    ; is built on top of BREADBOX.

    .proc {{ api_def("boot") }}
        sei                                    ; Disable interrupts.
        ldx #$ff                               ; Initialize stack pointer.
        txs
        cld                                    ; Disable decimal mode.
        jsr {{ my("call_constructors") }}      ; Call registered constructors.
        cli                                    ; Enable interrupts.
        jmp main                               ; Call main (exported by project).
    .endproc

    ; =========================================================================
    ; Call all registered constructors.
    ;
    ; The CONDES table is generated by ld65, sorted by descending priority.
    ; Each entry is 2 bytes: address low + address high.
    ; Uses the trampoline for indirect JSR calls.

    .proc {{ my("call_constructors") }}
        lda #<__CONSTRUCTOR_COUNT__
        beq @done

        ; Initialize pointer to constructor table.
        SET_POINTER {{ my("condes_ptr") }}, __CONSTRUCTOR_TABLE__

        ldx #<__CONSTRUCTOR_COUNT__
    @loop:
        ; Read address from table entry (2 bytes: lo, hi).
        ldy #0
        lda ({{ my("condes_ptr") }}),y          ; Address low byte.
        sta {{ my("constructor_ptr") }}
        iny
        lda ({{ my("condes_ptr") }}),y          ; Address high byte.
        sta {{ my("constructor_ptr") }} + 1

        ; Save counter, call constructor, restore counter.
        PUSH_X
        jsr {{ my("constructor_trampoline") }}
        PULL_X

        ; Advance pointer by 2 bytes (next entry).
        clc
        lda {{ my("condes_ptr") }}
        adc #2
        sta {{ my("condes_ptr") }}
        bcc @no_carry
        inc {{ my("condes_ptr") }}+1
    @no_carry:

        dex
        bne @loop

    @done:
        rts
    .endproc

    ; =========================================================================
    ; Classic 6502 JSR trampoline.
    ;
    ; The 6502 has no `JSR (indirect)` instruction. Work around this by
    ; doing a `jsr` into a subroutine (the trampoline) that then does a `jmp`
    ; to the target subroutine address. When that subroutine does its `rts`,
    ; the program pointer returns to the point from where the `jsr` was done.

    .proc {{ my("constructor_trampoline") }}
        jmp ({{ my("constructor_ptr") }})
    .endproc
