{{ symbol("VECTORS_S") }} = 1
.include "{{ device_path }}/api.inc"

.import {{ symbol("boot") }}             ; Import KERNAL boot subprocedure.
.import __INTERRUPTOR_TABLE__            ; Table generated by ld65 CONDES
.import __INTERRUPTOR_COUNT__            ; Number of interruptor entries

.exportzp {{ symbol("nmi_vector") }}
.exportzp {{ symbol("irq_vector") }}

.constructor {{ symbol("init_vectors") }}, 32  ; Add constructor, max prio.

.segment "ZEROPAGE"

    ; Address vectors, that can be modified in order to point
    ; to a custom interrupt handler.
    {{ symbol("nmi_vector") }}: .res 2
    {{ symbol("irq_vector") }}: .res 2
    {{ symbol("irq_ptr") }}:    .res 2   ; Target for IRQ dispatch trampoline

    ; Local aliases so the SET_NMI / SET_IRQ macros can resolve.
    nmi_vector = {{ symbol("nmi_vector") }}
    irq_vector = {{ symbol("irq_vector") }}

.segment "KERNAL"

    ; =========================================================================
    ; Setup the default vectors and interrupt handling.
    ;
    ; - Interrupts disabled (call `cli` to enable interrupts)
    ; - Reset vector pointing to boot subroutine
    ; - Null NMI handler
    ; - IRQ handler: interruptor table dispatcher
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("init_vectors") }}
        sei
        SET_NMI {{ symbol("null_interrupt_handler") }}
        SET_IRQ {{ symbol("dispatch_interruptors") }}
        rts
    .endproc

    ; =========================================================================
    ; Hardware vector entry points.
    ;
    ; NMI and IRQ dispatch through zero-page pointers, which can be
    ; redirected at runtime using the SET_NMI / SET_IRQ macros.

    {{ symbol("dispatch_nmi") }}:
        jmp ({{ symbol("nmi_vector") }})       ; Forward to configured NMI handler

    {{ symbol("dispatch_irq") }}:
        jmp ({{ symbol("irq_vector") }})       ; Forward to configured IRQ handler

    {{ symbol("null_interrupt_handler") }}:
        rti

    ; =========================================================================
    ; IRQ table dispatcher.
    ;
    ; Default IRQ handler that walks the CONDES interruptor table and
    ; calls each registered handler. Handlers are registered at link time
    ; using the `.interruptor` directive.
    ;
    ; Uses a dedicated ZP pointer ({{ symbol("irq_ptr") }}) and local trampoline to avoid
    ; sharing state with main-context code that may use the boot trampoline.
    ;
    ; Handlers must return with `rts`. Register saving and `rti` are
    ; handled here.
    ;
    ; A, X, Y = preserved

    .proc {{ symbol("dispatch_interruptors") }}
        PUSH_AXY

        lda #<__INTERRUPTOR_COUNT__
        beq @done

        ldy #0
        tax                        ; X = handler count

    @loop:
        lda __INTERRUPTOR_TABLE__,y
        sta {{ symbol("irq_ptr") }}
        iny
        lda __INTERRUPTOR_TABLE__,y
        sta {{ symbol("irq_ptr") }}+1
        iny

        ; Save table offset and counter across handler call.
        phy
        phx
        jsr {{ symbol("irq_trampoline") }}
        plx
        ply

        dex
        bne @loop

    @done:
        PULL_AXY
        rti
    .endproc

    .proc {{ symbol("irq_trampoline") }}
        jmp ({{ symbol("irq_ptr") }})
    .endproc

.segment "VECTORS"

    .word {{ symbol("dispatch_nmi") }}         ; Non-Maskable Interrupt vector
    .word {{ symbol("boot") }}                 ; Reset vector
    .word {{ symbol("dispatch_irq") }}         ; IRQ vector
