.include "{{ component_path }}/coding_macros.inc"
.include "{{ component_path }}/cpu_shims_macros.inc"

.import {{ api("boot") }}             ; Import KERNAL boot subprocedure.
.import __INTERRUPTOR_TABLE__            ; Table generated by ld65 CONDES
.import __INTERRUPTOR_COUNT__            ; Number of interruptor entries


.constructor {{ my("init_vectors") }}, 32  ; Add constructor, max prio.

.segment "ZEROPAGE"

    ; Address vectors, that can be modified in order to point
    ; to a custom interrupt handler.
    {{ zp_def("nmi_vector") }}: .res 2
    {{ zp_def("irq_vector") }}: .res 2
    {{ my("irq_ptr") }}:        .res 2   ; Target for IRQ dispatch trampoline

.segment "KERNALROM"

    ; =========================================================================
    ; Setup the default vectors and interrupt handling.
    ;
    ; - Interrupts enabled by boot if interruptors are registered
    ; - Reset vector pointing to boot subroutine
    ; - Null NMI handler
    ; - IRQ handler: interruptor table dispatcher
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ my("init_vectors") }}
        sei
        SET_POINTER {{ zp("nmi_vector") }}, {{ my("null_interrupt_handler") }}
        SET_POINTER {{ zp("irq_vector") }}, {{ my("dispatch_interruptors") }}
        rts
    .endproc

    ; =========================================================================
    ; Hardware vector entry points.
    ;
    ; NMI and IRQ dispatch through zero-page pointers, which can be
    ; redirected at runtime using the SET_NMI / SET_IRQ macros.

    {{ my("dispatch_nmi") }}:
        jmp ({{ api("nmi_vector") }})       ; Forward to configured NMI handler

    {{ my("dispatch_irq") }}:
        jmp ({{ api("irq_vector") }})       ; Forward to configured IRQ handler

    {{ my("null_interrupt_handler") }}:
        rti

    ; =========================================================================
    ; IRQ table dispatcher.
    ;
    ; Default IRQ handler that walks the CONDES interruptor table and
    ; calls each registered handler. Handlers are registered at link time
    ; using the `.interruptor` directive.
    ;
    ; Uses a dedicated ZP pointer ({{ symbol("irq_ptr") }}) and local trampoline to avoid
    ; sharing state with main-context code that may use the boot trampoline.
    ;
    ; Handlers must return with `rts`. Register saving and `rti` are
    ; handled here.
    ;
    ; A, X, Y = preserved

    .proc {{ my("dispatch_interruptors") }}
        PUSH_AXY

        lda #<__INTERRUPTOR_COUNT__
        beq @done

        ldy #0
        tax                        ; X = handler count

    @loop:
        lda __INTERRUPTOR_TABLE__,y
        sta {{ my("irq_ptr") }}
        iny
        lda __INTERRUPTOR_TABLE__,y
        sta {{ my("irq_ptr") }}+1
        iny

        ; Save table offset and counter across handler call.
        phy
        phx
        jsr {{ my("irq_trampoline") }}
        plx
        ply

        dex
        bne @loop

    @done:
        PULL_AXY
        rti
    .endproc

    .proc {{ my("irq_trampoline") }}
        jmp ({{ my("irq_ptr") }})
    .endproc

.segment "VECTORS"

    .word {{ my("dispatch_nmi") }}         ; Non-Maskable Interrupt vector
    .word {{ my("boot") }}                 ; Reset vector
    .word {{ my("dispatch_irq") }}         ; IRQ vector
