__CORE_VECTORS_S = 1
.include "core/vectors.inc"

.import __core_boot                  ; Import KERNAL boot subprocedure.
.import __INTERRUPTOR_TABLE__        ; Interruptor table (generated by ld65 CONDES)
.import __INTERRUPTOR_COUNT__        ; Number of interruptor entries

.constructor init_vectors, 32        ; Add constructor, max prio to run early.

.segment "ZEROPAGE"

    ; Address vectors, that can be modified in order to point
    ; to a custom interrupt handler.
    nmi_vector: .res 2
    irq_vector: .res 2
    _irq_ptr:   .res 2              ; Target pointer for IRQ dispatch trampoline
.exportzp __core_nmi_vector = nmi_vector
.exportzp __core_irq_vector = irq_vector

.segment "KERNAL"

    ; =========================================================================
    ; Setup the default vectors and interrupt handling.
    ; 
    ; - Interrupts disabled (call `cli` to enable interrupts)
    ; - Reset vector pointing to boot subroutine
    ; - Null NMI handler
    ; - IRQ handler: interruptor table dispatcher
    ;
    ; Out:
    ;   A = clobbered

    .proc init_vectors
        sei
        SET_NMI null_interrupt_handler
        SET_IRQ _dispatch_interruptors
        rts
    .endproc

    ; =========================================================================
    ; Hardware vector entry points.
    ;
    ; NMI and IRQ dispatch through zero-page pointers, which can be
    ; redirected at runtime using the SET_NMI / SET_IRQ macros.

    dispatch_nmi:
        jmp (nmi_vector)       ; Forward to configured NMI handler

    dispatch_irq:
        jmp (irq_vector)       ; Forward to configured IRQ handler

    null_interrupt_handler:
        rti

    ; =========================================================================
    ; IRQ table dispatcher.
    ;
    ; Default IRQ handler that walks the CONDES interruptor table and
    ; calls each registered handler. Handlers are registered at link time
    ; using the `.interruptor` directive.
    ;
    ; Uses a dedicated ZP pointer (_irq_ptr) and local trampoline to avoid
    ; sharing state with main-context code that may use the boot trampoline.
    ;
    ; Handlers must return with `rts`. Register saving and `rti` are
    ; handled here.
    ;
    ; Preserves: all registers.

    .proc _dispatch_interruptors
        pha
        txa
        pha
        tya
        pha

        lda #<__INTERRUPTOR_COUNT__
        beq @done

        ldy #0
        tax                        ; X = handler count

    @loop:
        lda __INTERRUPTOR_TABLE__,y
        sta _irq_ptr
        iny
        lda __INTERRUPTOR_TABLE__,y
        sta _irq_ptr+1
        iny

        ; Save table offset and counter across handler call.
        tya
        pha
        txa
        pha
        jsr _irq_trampoline
        pla
        tax
        pla
        tay

        dex
        bne @loop

    @done:
        pla
        tay
        pla
        tax
        pla
        rti
    .endproc

    .proc _irq_trampoline
        jmp (_irq_ptr)
    .endproc

.segment "VECTORS"

    .word dispatch_nmi         ; Non-Maskable Interrupt vector
    .word __core_boot          ; Reset vector
    .word dispatch_irq         ; IRQ vector
