; Auto-generated by breadbox. Do not edit.
; GPIO pin: {{ device_id }} ({{ pin }} on {{ bus_device.id }}, port {{ port }})
;
; Subroutine wrappers for {{ device_id }} macros.
; Call via JSR, e.g. `jsr {{ device_id }}::turn_on`.

.include "breadbox.inc"

.segment "KERNAL"

.scope {{ device_id }}
{% if direction in ("out", "both") %}

    ; =====================================================================
    ; Set {{ device_id }} output high.
    ;
    ; Out:
    ;   A = clobbered

    .proc turn_on
        {{ device_id }}_on
        rts
    .endproc

    ; =====================================================================
    ; Set {{ device_id }} output low.
    ;
    ; Out:
    ;   A = clobbered

    .proc turn_off
        {{ device_id }}_off
        rts
    .endproc

    ; =====================================================================
    ; Toggle {{ device_id }} output.
    ;
    ; Out:
    ;   A = clobbered

    .proc toggle
        {{ device_id }}_toggle
        rts
    .endproc
{% endif %}
{% if direction in ("in", "both") %}

    ; =====================================================================
    ; Read {{ device_id }} input state.
    ;
    ; Out:
    ;   A = pin state (bit {{ pin[-1] }}, masked)

    .proc read
        {{ device_id }}_read
        rts
    .endproc
{% endif %}
.endscope
