; Auto-generated by breadbox. Do not edit.
; GPIO pin: {{ device_id }} ({{ pin }} on {{ bus_device.id }}, port {{ port }})
;
; Subroutine wrappers for {{ device_id }} macros.
; Call via JSR, e.g. `jsr {{ device_id }}::turn_on`.

.include "breadbox.inc"

{% set PORT_REG = bus_device.id ~ "_PORT" ~ port %}
{% set DDR_REG = bus_device.id ~ "_DDR" ~ port %}
{% set MASK = bitmask %}
{% set INV_MASK = 255 - bitmask %}
.segment "KERNAL"
{% if default is not none %}

; =========================================================================
; Initialize {{ device_id }}: set DDR to output and apply default ({{ default }}).
;
; Called automatically during boot via .constructor.
;
; Out:
;   A = clobbered

    .proc init_{{ device_id | lower }}
{% if exclusive_port %}
        lda #{{ MASK | hex }}
        sta {{ DDR_REG }}
{% if default == "on" %}
        sta {{ PORT_REG }}
{% else %}
        lda #$00
        sta {{ PORT_REG }}
{% endif %}
{% else %}
        lda {{ DDR_REG }}
        ora #{{ MASK | hex }}
        sta {{ DDR_REG }}
{% if default == "on" %}
        lda {{ PORT_REG }}
        ora #{{ MASK | hex }}
        sta {{ PORT_REG }}
{% else %}
        lda {{ PORT_REG }}
        and #{{ INV_MASK | hex }}
        sta {{ PORT_REG }}
{% endif %}
{% endif %}
        rts
    .endproc
    .constructor init_{{ device_id | lower }}
{% endif %}

.scope {{ device_id }}
{% if direction in ("out", "both") %}

    ; =====================================================================
    ; Set {{ device_id }} output high.
    ;
    ; Out:
    ;   A = clobbered

    .proc turn_on
        {{ device_id }}_on
        rts
    .endproc

    ; =====================================================================
    ; Set {{ device_id }} output low.
    ;
    ; Out:
    ;   A = clobbered

    .proc turn_off
        {{ device_id }}_off
        rts
    .endproc

    ; =====================================================================
    ; Toggle {{ device_id }} output.
    ;
    ; Out:
    ;   A = clobbered

    .proc toggle
        {{ device_id }}_toggle
        rts
    .endproc
{% endif %}
{% if direction in ("in", "both") %}

    ; =====================================================================
    ; Read {{ device_id }} input state.
    ;
    ; Out:
    ;   A = pin state (bit {{ pin[-1] }}, masked)

    .proc read
        {{ device_id }}_read
        rts
    .endproc
{% endif %}
.endscope
