; Auto-generated by breadbox. Do not edit.
; GPIO pin: {{ component_id }} ({{ pin }} on {{ bus_device.id }}, port {{ port }})
;
; Subroutine wrappers for {{ component_id }} macros.
; Call via JSR, e.g. `jsr {{ symbol_prefix }}::turn_on`.

.include "hardware.inc"
.include "{{ component_path }}/macros.inc"

{% set PORT_REG = bus_device.id ~ "_PORT" ~ port %}
{% set DDR_REG = bus_device.id ~ "_DDR" ~ port %}
{% set MASK = bitmask %}
{% set INV_MASK = 255 - bitmask %}
.segment "KERNALROM"
{% if direction in ("out", "both") or default is not none %}

    ; =========================================================================
    ; Initialize {{ component_id }}: set DDR to output{% if default is not none %} and apply default ({{ default }}){% endif %}.
    ;
    ; Called automatically during boot via .constructor.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ my_def("init") }}
{% if exclusive_port %}
        lda #{{ MASK | hex }}
        sta {{ DDR_REG }}
{% if default == "on" %}
        sta {{ PORT_REG }}
{% elif default == "off" %}
        lda #$00
        sta {{ PORT_REG }}
{% endif %}
{% else %}
        lda {{ DDR_REG }}
        ora #{{ MASK | hex }}
        sta {{ DDR_REG }}
{% if default == "on" %}
        lda {{ PORT_REG }}
        ora #{{ MASK | hex }}
        sta {{ PORT_REG }}
{% elif default == "off" %}
        lda {{ PORT_REG }}
        and #{{ INV_MASK | hex }}
        sta {{ PORT_REG }}
{% endif %}
{% endif %}
        rts
    .endproc
    .constructor {{ my("init") }}, 16
{% endif %}

{% if direction in ("out", "both") %}
    ; =====================================================================
    ; Set {{ component_id }} output high.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ api_def("turn_on") }}
        {{ symbol_prefix }}_on
        rts
    .endproc

    ; =====================================================================
    ; Set {{ component_id }} output low.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ api_def("turn_off") }}
        {{ symbol_prefix }}_off
        rts
    .endproc

    ; =====================================================================
    ; Toggle {{ component_id }} output.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ api_def("toggle") }}
        {{ symbol_prefix }}_toggle
        rts
    .endproc
{% endif %}
{% if direction in ("in", "both") %}

    ; =====================================================================
    ; Read {{ component_id }} input state.
    ;
    ; Out:
    ;   A = pin state (bit {{ pin[-1] }}, masked)

    .proc {{ api_def("read") }}
        {{ symbol_prefix }}_read
        rts
    .endproc
{% endif %}
