; Auto-generated by breadbox. Do not edit.
; GPIO pin: {{ device_id }} ({{ pin }} on {{ bus_device.id }}, port {{ port }})
;
; Subroutine wrappers for {{ device_id }} macros.
; Call via JSR, e.g. `jsr {{ macro_prefix }}::turn_on`.

.include "hardware.inc"
.include "{{ device_path }}/macros.inc"

{% set PORT_REG = bus_device.id ~ "_PORT" ~ port %}
{% set DDR_REG = bus_device.id ~ "_DDR" ~ port %}
{% set MASK = bitmask %}
{% set INV_MASK = 255 - bitmask %}
.segment "KERNAL"
{% if direction in ("out", "both") or default is not none %}

    ; =========================================================================
    ; Initialize {{ device_id }}: set DDR to output{% if default is not none %} and apply default ({{ default }}){% endif %}.
    ;
    ; Called automatically during boot via .constructor.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("init") }}
{% if exclusive_port %}
        lda #{{ MASK | hex }}
        sta {{ DDR_REG }}
{% if default == "on" %}
        sta {{ PORT_REG }}
{% elif default == "off" %}
        lda #$00
        sta {{ PORT_REG }}
{% endif %}
{% else %}
        lda {{ DDR_REG }}
        ora #{{ MASK | hex }}
        sta {{ DDR_REG }}
{% if default == "on" %}
        lda {{ PORT_REG }}
        ora #{{ MASK | hex }}
        sta {{ PORT_REG }}
{% elif default == "off" %}
        lda {{ PORT_REG }}
        and #{{ INV_MASK | hex }}
        sta {{ PORT_REG }}
{% endif %}
{% endif %}
        rts
    .endproc
    .constructor {{ symbol("init") }}, 16
{% endif %}

{% if direction in ("out", "both") %}
    ; =====================================================================
    ; Set {{ device_id }} output high.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("turn_on") }}
        {{ macro_prefix }}_on
        rts
    .endproc

    ; =====================================================================
    ; Set {{ device_id }} output low.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("turn_off") }}
        {{ macro_prefix }}_off
        rts
    .endproc

    ; =====================================================================
    ; Toggle {{ device_id }} output.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("toggle") }}
        {{ macro_prefix }}_toggle
        rts
    .endproc
{% endif %}
{% if direction in ("in", "both") %}

    ; =====================================================================
    ; Read {{ device_id }} input state.
    ;
    ; Out:
    ;   A = pin state (bit {{ pin[-1] }}, masked)

    .proc {{ symbol("read") }}
        {{ macro_prefix }}_read
        rts
    .endproc
{% endif %}

; =========================================================================
; Exports
; =========================================================================

{% if direction in ("out", "both") %}
{{ export("turn_on") }}
{{ export("turn_off") }}
{{ export("toggle") }}
{% endif %}
{% if direction in ("in", "both") %}
{{ export("read") }}
{% endif %}
