CPU: # Special name, triggers automatic selection of component "cpu".
  #component: cpu # <-- therefore this line could be omitted.
  type: 65c02
  clock_mhz: 1.0

# First "bus" device.
VIA0:
  component: via_w65c22
  address: $6000

# Second "bus" device.
VIA1:
  component: via_w65c22
  address: $6100

STATUS_LED:
  component: gpio_pin  # the via0 component has to handle this for codegen
  bus: VIA0
  direction: out   # limits generated code to only output macros
  pin: PA0    # Automatically derives use of Port A on the via0 bus

 # A group of GPIO pins that can be switched together.
PROGRESS_LEDS:
  component: gpio_group  # the VIA1 component has to handle this for codegen.
  bus: VIA1
  direction: out
  default: OFF
  port: A
  bits: [0, 2, 6, 7]

SOME_8BIT_PORT:
  component: gpio_group
  bus: VIA0
  port: A
  bits: [0, 1, 2, 3, 4, 5, 6, 7]   #  maybe other formats too. $ff, "11111111", 255, "all" ...
  default: off
  direction: out


LCD0:
  component: lcd_hd44780
  cmnd:
    bus: VIA0
    rwb_pin: PA5
    en_pin: PA6
    rs_pin: PA7
  data:
    bus: VIA1
    mode: 8bit
    port: B       # 4- bit mode uses pins 4-7, 8-bit mode uses all pins.
