; Auto-generated by breadbox. Do not edit.
; GPIO group: {{ device_id }} (port {{ port }} on {{ bus_device.id }}, mask {{ bits | hex }})
;
; Subroutine wrappers for {{ device_id }} macros.
; Call via JSR, e.g. `jsr {{ macro_prefix }}::turn_on`.

__{{ macro_prefix | upper }}_IMPL = 1
.include "breadbox.inc"

{% set PORT_REG = bus_device.id ~ "_PORT" ~ port %}
{% set DDR_REG = bus_device.id ~ "_DDR" ~ port %}
{% set MASK = bits | int %}
{% set INV_MASK = 255 - MASK %}
.segment "KERNAL"
{% if default is not none %}

    ; =========================================================================
    ; Initialize {{ device_id }}: set DDR to output and apply default ({{ default }}).
    ;
    ; Called automatically during boot via .constructor.
    ;
    ; Out:
    ;   A = clobbered

    .proc init_{{ macro_prefix | lower }}
{% if exclusive_port %}
        lda #{{ MASK | hex }}
        sta {{ DDR_REG }}
{% if default == "on" %}
        sta {{ PORT_REG }}
{% else %}
        lda #$00
        sta {{ PORT_REG }}
{% endif %}
{% else %}
        lda {{ DDR_REG }}
        ora #{{ MASK | hex }}
        sta {{ DDR_REG }}
{% if default == "on" %}
        lda {{ PORT_REG }}
        ora #{{ MASK | hex }}
        sta {{ PORT_REG }}
{% else %}
        lda {{ PORT_REG }}
        and #{{ INV_MASK | hex }}
        sta {{ PORT_REG }}
{% endif %}
{% endif %}
        rts
    .endproc
    .constructor init_{{ macro_prefix | lower }}
{% endif %}

{% if direction in ("out", "both") %}
    ; =====================================================================
    ; Set all {{ device_id }} outputs high.
    ;
    ; Out:
    ;   A = clobbered

    .proc _{{ macro_prefix }}_turn_on
        {{ macro_prefix }}_on
        rts
    .endproc

    ; =====================================================================
    ; Set all {{ device_id }} outputs low.
    ;
    ; Out:
    ;   A = clobbered

    .proc _{{ macro_prefix }}_turn_off
        {{ macro_prefix }}_off
        rts
    .endproc

    ; =====================================================================
    ; Toggle all {{ device_id }} outputs.
    ;
    ; Out:
    ;   A = clobbered

    .proc _{{ macro_prefix }}_toggle
        {{ macro_prefix }}_toggle
        rts
    .endproc
{% endif %}
{% if direction in ("in", "both") %}

    ; =====================================================================
    ; Read {{ device_id }} input state.
    ;
    ; Out:
    ;   A = group state (masked to {{ bits | hex }})

    .proc _{{ macro_prefix }}_read
        {{ macro_prefix }}_read
        rts
    .endproc
{% endif %}

; =========================================================================
; Exports
; =========================================================================

{% if direction in ("out", "both") %}
.export __{{ macro_prefix }}_turn_on  = _{{ macro_prefix }}_turn_on
.export __{{ macro_prefix }}_turn_off = _{{ macro_prefix }}_turn_off
.export __{{ macro_prefix }}_toggle   = _{{ macro_prefix }}_toggle
{% endif %}
{% if direction in ("in", "both") %}
.export __{{ macro_prefix }}_read     = _{{ macro_prefix }}_read
{% endif %}
