; Auto-generated by breadbox. Do not edit.
; GPIO group: {{ device_id }} (port {{ port }} on {{ bus_device.id }}, mask {{ bits | hex }})
;
; Subroutine wrappers for {{ device_id }} macros.
; Call via JSR, e.g. `jsr {{ device_id }}::turn_on`.

.include "breadbox.inc"

.segment "KERNAL"

.scope {{ device_id }}
{% if direction in ("out", "both") %}

    ; =====================================================================
    ; Set all {{ device_id }} outputs high.
    ;
    ; Out:
    ;   A = clobbered

    .proc turn_on
        {{ device_id }}_on
        rts
    .endproc

    ; =====================================================================
    ; Set all {{ device_id }} outputs low.
    ;
    ; Out:
    ;   A = clobbered

    .proc turn_off
        {{ device_id }}_off
        rts
    .endproc

    ; =====================================================================
    ; Toggle all {{ device_id }} outputs.
    ;
    ; Out:
    ;   A = clobbered

    .proc toggle
        {{ device_id }}_toggle
        rts
    .endproc
{% endif %}
{% if direction in ("in", "both") %}

    ; =====================================================================
    ; Read {{ device_id }} input state.
    ;
    ; Out:
    ;   A = group state (masked to {{ bits | hex }})

    .proc read
        {{ device_id }}_read
        rts
    .endproc
{% endif %}
.endscope
