; Auto-generated by breadbox. Do not edit.
; GPIO group: {{ component_id }} (port {{ port }} on {{ bus_device.id }}, mask {{ bits | hex }})
;
; Subroutine wrappers for {{ component_id }} macros.
; Call via JSR, e.g. `jsr {{ symbol_prefix }}::turn_on`.

.exportzp {{ symbol("tmp") }}

{% if direction in ("out", "both") %}
.export {{ symbol("turn_on") }}
.export {{ symbol("turn_off") }}
.export {{ symbol("toggle") }}
.export {{ symbol("write_a") }}
{% endif %}

{% if direction in ("in", "both") %}
.export {{ symbol("read") }}
.export {{ symbol("read_port") }}
{% endif %}

{% if direction == "both" %}
.export {{ symbol("set_output") }}
.export {{ symbol("set_input") }}
{% endif %}

{% set P = symbol_prefix %}

.segment "KERNALZP" : zeropage

{{ symbol("tmp") }}: .res 1                   ; Internal temporary for read-modify-write

.include "hardware.inc"
.include "{{ component_path }}/macros.inc"

.segment "KERNALROM"
{% if direction in ("out", "both") or default is not none %}

    ; =========================================================================
    ; Initialize {{ component_id }}: set DDR to output{% if default is not none %} and apply default ({{ default }}){% endif %}.
    ;
    ; Called automatically during boot via .constructor.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("init") }}
{% if exclusive_port %}
        lda #{{ bits | hex }}
        sta {{ bus_device.id }}_DDR{{ port }}
{% if default == "on" %}
        sta {{ bus_device.id }}_PORT{{ port }}
{% elif default == "off" %}
        lda #$00
        sta {{ bus_device.id }}_PORT{{ port }}
{% endif %}
{% else %}
        lda {{ bus_device.id }}_DDR{{ port }}
        ora #{{ bits | hex }}
        sta {{ bus_device.id }}_DDR{{ port }}
{% if default == "on" %}
        lda {{ bus_device.id }}_PORT{{ port }}
        ora #{{ bits | hex }}
        sta {{ bus_device.id }}_PORT{{ port }}
{% elif default == "off" %}
        lda {{ bus_device.id }}_PORT{{ port }}
        and #{{ (255 - (bits | int)) | hex }}
        sta {{ bus_device.id }}_PORT{{ port }}
{% endif %}
{% endif %}
        rts
    .endproc
    .constructor {{ symbol("init") }}, 16
{% endif %}
{% if direction in ("out", "both") %}

    ; =====================================================================
    ; Set all {{ component_id }} outputs high.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("turn_on") }}
        {{ P }}_on
        rts
    .endproc

    ; =====================================================================
    ; Set all {{ component_id }} outputs low.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("turn_off") }}
        {{ P }}_off
        rts
    .endproc

    ; =====================================================================
    ; Toggle all {{ component_id }} outputs.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("toggle") }}
        {{ P }}_toggle
        rts
    .endproc

    ; =====================================================================
    ; Write the accumulator to {{ component_id }}.
    ;
    ; In:
    ;   A = byte value to write (pre-positioned in {{ bits | hex }})
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("write_a") }}
        {{ P }}_write_a
        rts
    .endproc
{% endif %}
{% if direction in ("in", "both") %}

    ; =====================================================================
    ; Read {{ component_id }} input state (with DDR handling).
    ;
    ; Out:
    ;   A = group state (masked to {{ bits | hex }})

    .proc {{ symbol("read") }}
        {{ P }}_read
        rts
    .endproc

    ; =====================================================================
    ; Read {{ component_id }} port value without changing DDR.
    ;
    ; Out:
    ;   A = group state (masked to {{ bits | hex }})

    .proc {{ symbol("read_port") }}
        {{ P }}_read_port
        rts
    .endproc
{% endif %}
{% if direction == "both" %}

    ; =====================================================================
    ; Switch {{ component_id }} DDR to output mode.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("set_output") }}
        {{ P }}_set_output
        rts
    .endproc

    ; =====================================================================
    ; Switch {{ component_id }} DDR to input mode.
    ;
    ; Out:
    ;   A = clobbered

    .proc {{ symbol("set_input") }}
        {{ P }}_set_input
        rts
    .endproc
{% endif %}
