CORE:
  cpu: 65c02
  clock_mhz: 1.000

VIA:
  component: via_w65c22
  address: $6000

LED:
  component: gpio_pin
  bus: VIA
  pin: PA0
  direction: out
  default: on

PB0_IN:
  component: gpio_pin
  bus: VIA
  pin: PB0
  direction: in

PB1_OUT:
  component: gpio_pin
  bus: VIA
  pin: PB1
  direction: out

PB2_BOTH:
  component: gpio_pin
  bus: VIA
  pin: PB2
  direction: both


