CORE:
  cpu: "65c02"
  clock_mhz: 1.000

VIA:
  component: via_w65c22
  address: $6000

TICKER:
  component: ticker
  provider: VIA
  ms_per_tick: 10
  timers:
    led_toggle_timer: 1000
    lcd_update_timer: 100

LCD:
  component: lcd_hd44780
  cmnd_pins:
    provider: VIA
    rs_pin: PB0
    rwb_pin: PB1
    en_pin: PB2
  data_pins:
    provider: VIA
    mode: 4bit
    port: B

LED:
  component: gpio_pin
  provider: VIA
  pin: PA1
  direction: out
  default: off

SERIAL:
  component: uart_6551
  type: um6551
  address: $5000
  irq: on
  rts:
    provider: VIA
    pin: PA0

TERMINAL:
  component: terminal
  provider: SERIAL
