CORE:
  cpu: 65c02
  clock_mhz: 1.000

VIA:
  component: via_w65c22
  address: $6000

LCD:
  component: lcd_hd44780
  cmnd_pins:
    provider: VIA
    rs_pin: PB0
    rwb_pin: PB1
    en_pin: PB2
  data_pins:
    provider: VIA
    mode: 4bit
    port: B

LCD_SCREEN:
  component: screen
  provider: LCD

SERIAL:
  component: uart_6551
  type: um6551
  address: $5000
  baudrate: 19200
  irq: on
  rts:
    provider: VIA
    pin: PA0
    
SERIAL_SCREEN:
  component: screen
  provider: SERIAL

SERIAL_KEYBOARD:
  component: keyboard
  provider: SERIAL

TERMINAL:
  component: tty
  keyboard: SERIAL_KEYBOARD
  screen: SERIAL_SCREEN

