from pathlib import Path

from breadbox.config import Device, GpioGroup, GpioPin, HardwareConfig
from breadbox.drivers.w65c22 import (
    generate_constants,
    generate_gpio_group_macros,
    generate_gpio_pin_macros,
    generate_init,
)

DRIVERS = {"w65c22"}

HEADER = "; Auto-generated by breadbox. Do not edit."


def _generate_device_inc(device: Device) -> list[str]:
    lines = []
    lines += generate_constants(device)
    lines.append("")

    for name, logical in device.provides.items():
        if isinstance(logical, GpioPin):
            lines += generate_gpio_pin_macros(name, device, logical)
        elif isinstance(logical, GpioGroup):
            lines += generate_gpio_group_macros(name, device, logical)
        lines.append("")

    return lines


def _generate_device_s(device: Device) -> list[str]:
    lines = [
        '.include "generated/hardware.inc"',
        "",
        '.segment "KERNAL"',
        "",
    ]
    lines += generate_init(device)
    return lines


def generate(config: HardwareConfig, output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)

    for device in config.devices:
        if device.driver not in DRIVERS:
            supported = ", ".join(DRIVERS)
            raise ValueError(
                f"Unknown driver '{device.driver}' for device '{device.name}' "
                f"(supported: {supported})"
            )

    inc_lines = [HEADER, ""]
    inc_lines += [
        f'.setcpu "{config.cpu.type}"',
        f"CPU_CLOCK = {config.cpu.clock_hz}",
        "",
    ]

    s_lines = [HEADER, ""]

    for device in config.devices:
        inc_lines += _generate_device_inc(device)
        s_lines += _generate_device_s(device)

    inc_path = output_dir / "hardware.inc"
    s_path = output_dir / "hardware.s"

    inc_path.write_text("\n".join(inc_lines) + "\n")
    s_path.write_text("\n".join(s_lines) + "\n")

    return [inc_path, s_path]
