"""
Memory map parsing and export.

Parses the ld65 map file to extract segment placement, and exports a
clean memory map showing where each segment was placed and what address
ranges are available for user code.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from breadbox.memory import MemoryLayout


@dataclass(frozen=True)
class SegmentEntry:
    """A segment as placed by the linker."""

    name: str
    start: int
    end: int  # inclusive
    size: int


def parse_ld65_map(map_text: str) -> list[SegmentEntry]:
    """
    Parse the 'Segment list' section from ld65 map output.

    Returns a list of SegmentEntry sorted by start address.
    """
    entries: list[SegmentEntry] = []

    in_segment_list = False
    past_header = False
    for line in map_text.splitlines():
        if line.startswith("Segment list:"):
            in_segment_list = True
            continue
        if in_segment_list and line.startswith("----"):
            past_header = True
            continue
        if in_segment_list and past_header:
            if not line.strip():
                break  # End of segment list section
            match = re.match(
                r"(\S+)\s+([0-9A-Fa-f]+)\s+([0-9A-Fa-f]+)\s+([0-9A-Fa-f]+)\s+",
                line,
            )
            if match:
                name = match.group(1)
                start = int(match.group(2), 16)
                end = int(match.group(3), 16)
                size = int(match.group(4), 16)
                entries.append(SegmentEntry(name=name, start=start, end=end, size=size))

    entries.sort(key=lambda e: (e.start, e.name))
    return entries


def format_memory_map(segments: list[SegmentEntry], layout: MemoryLayout) -> str:
    """
    Format a clean memory map for export.

    Groups segments by their memory region and shows the address ranges.
    Highlights where user-available space begins.
    """
    # Build a lookup: segment name -> memory region name
    seg_to_region: dict[str, str] = {}
    for seg in layout.segments:
        seg_to_region[seg.name] = seg.load

    # Build a lookup: region name -> (start, end_exclusive)
    region_bounds: dict[str, tuple[int, int]] = {}
    for region in layout.regions:
        region_bounds[region.name] = (region.start, region.start + region.size)

    lines: list[str] = []
    lines.append("# Memory map - generated by breadbox build")
    lines.append("#")
    lines.append("# This file shows where each segment was placed by the linker.")
    lines.append("# Use the free ranges for separate app builds.")
    lines.append("")

    # Group placed segments by region
    region_segments: dict[str, list[SegmentEntry]] = {}
    for entry in segments:
        region_name = seg_to_region.get(entry.name, "?")
        region_segments.setdefault(region_name, []).append(entry)

    # Output each region with its segments
    for region in layout.regions:
        r_start, r_end = region_bounds[region.name]
        lines.append(f"[{region.name}]  ${r_start:04X}-${r_end - 1:04X}  ({r_end - r_start} bytes, {region.type})")

        placed = region_segments.get(region.name, [])
        for entry in placed:
            if entry.size > 0:
                lines.append(f"  {entry.name:<20s}  ${entry.start:04X}-${entry.end:04X}  ({entry.size} bytes)")
            else:
                lines.append(f"  {entry.name:<20s}  (empty)")

        # Calculate free space at end of region
        if placed:
            last_end = max(e.end + 1 for e in placed if e.size > 0)
        else:
            last_end = r_start
        free = r_end - last_end
        if free > 0:
            lines.append(f"  {'(free)':<20s}  ${last_end:04X}-${r_end - 1:04X}  ({free} bytes)")

        lines.append("")

    lines.append("")
    return "\n".join(lines)


def write_memory_map(
    ld65_map_path: Path,
    output_path: Path,
    layout: MemoryLayout,
) -> list[SegmentEntry]:
    """
    Read ld65 map file, produce a clean memory map, and write it.

    Returns the parsed segment entries.
    """
    map_text = ld65_map_path.read_text()
    segments = parse_ld65_map(map_text)
    content = format_memory_map(segments, layout)
    output_path.write_text(content)
    return segments
