CORE:
  cpu: "65c02"
  clock_mhz: 1.000

VIA:
  component: via_w65c22
  address: $6000

LCD:
  component: lcd_hd44780
  cmnd:
    parent: VIA
    rs_pin: PB0
    rwb_pin: PB1
    en_pin: PB2
  data:
    parent: VIA
    mode: 4bit
    port: B

LED:
  component: gpio_pin
  parent: VIA
  pin: PA0
  direction: out
  default: off

TICKER:
  component: ticker
  parent: VIA
